window.playerI18n = {
    restart: 'Рестарт',
    rewind: '{seektime}с назад',
    play: 'Воспроизведение',
    pause: 'Пауза',
    fastForward: '{seektime}с вперёд',
    seek: 'Seek',
    seekLabel: '{currentTime} из {duration}',
    played: 'Игран',
    buffered: 'Буферизован',
    currentTime: 'Текущее время',
    duration: 'Продолжительность',
    volume: 'Громкость',
    mute: 'Отключить звук',
    unmute: 'Включить звук',
    enableCaptions: 'Включить субтитров',
    disableCaptions: 'Отключить субтитров',
    enterFullscreen: 'Войти в полноэкранный режим',
    exitFullscreen: 'Выйти из полноэкранного режима',
    frameTitle: 'Плеер: {title}',
    captions: 'Субтитры',
    settings: 'Настройки',
    pip: 'PIP',
    menuBack: 'Вернуться в предыдущее меню',
    speed: 'Скорость',
    normal: '1x',
    quality: 'Качество',
    loop: 'Повторить',
    start: 'Начало',
    end: 'Финиш',
    all: 'Все',
    reset: 'Сбросить',
    disabled: 'Выкл.',
    enabled: 'Вкл.',
    watched: 'просмотрено',
    grid_prepared: 'Видео готовится',
    grid_error: 'Процесс наложения защиты завершен c ошибкой.',
    contact_support: 'Обратитесь в поддержку.',
    qualityBadge: {
        1080: 'HD',
        720: 'HD',
        576: 'SD',
        480: 'SD',
    },
    createPersonalVideo: "Получить персональное видео"
}
